// Copyright xTear Studios
/*-------------------------------------------------------------------------*/
#pragma once
#include "Items/Inv_ItemTags.h"
#include "Inv_EnumTypes.h"
#include "Inv_StructTypes.generated.h"
/*-------------------------------------------------------------------------*/



/*-------------------------------------------------------------------------*/
/*  Declarations										                   */
/*-------------------------------------------------------------------------*/
USTRUCT(BlueprintType)
struct FInv_ItemDefinition
{
	GENERATED_BODY()
	
	UPROPERTY()
	FName ID;
    
	UPROPERTY()
	FName IconID; // TODO: Not implemented at all yet.
    
	UPROPERTY()
	FString ItemName;
    
	UPROPERTY()
	FString ItemDescription;
    
	UPROPERTY()
	EInv_ItemRarity ItemRarity{EInv_ItemRarity::Common}; // Preinitialized to common.
    
	UPROPERTY()
	int32 SellValueBase;
    
	UPROPERTY()
	int MaxStackSize;
    
	UPROPERTY()
	int Durability;
    
	UPROPERTY()
	FGameplayTag ItemType;
};

USTRUCT(BlueprintType)
struct FInv_ItemAttributePair
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, Category = "Inventory", meta = (Categories= "Attributes" ))
	FGameplayTag AttributeTag{FGameplayTag::EmptyTag};	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	int32 Value{0};
	
	UPROPERTY(EditAnywhere, Category = "Inventory", meta = (Categories= "FragmentTags.StatMod" ))
	FGameplayTag FragmentTag{FGameplayTag::EmptyTag};
};

USTRUCT(BlueprintType)
struct FInv_SecondaryAttributeKey
{
	GENERATED_BODY()

	EInv_AttributeEntry AttributeEntry;
	EInv_AttributeScalarPower AttributeScalarPower;
	int AttributeLevel;
};

USTRUCT(BlueprintType)
struct FInv_ItemAbilityPair
{
	GENERATED_BODY()

	// TODO: Make this do something and mean something.
};

USTRUCT(BlueprintType)
struct FInv_ItemRNGResult
{
	GENERATED_BODY()
	/*-------------------------------------------------------------------------------*/
	/*  Item RNG Result																 */
	/*-------------------------------------------------------------------------------*/
	/* A struct of this type is created when an item is created. It can be predefined,
	 * or it can be autogenerated from a chest loot table. Either way, this is used
	 * by the GenerateItemData function to specify stars, enhancement, and special
	 * type rules. */
	/*-------------------------------------------------------------------------------*/

	// TODO: Make this useful.
	
};

USTRUCT(BlueprintType)
struct FInv_ItemSecondaryAttributeRules
{
	GENERATED_BODY()
	/*-------------------------------------------------------------------------------*/
	/*  Secondary Attribute Rules													 */
	/*-------------------------------------------------------------------------------*/
	/* A struct of this type is used for an item when creating the secondary attribute
	 * set. The reason for these rules is that some items may tend to lean towards
	 * specific stats as their sub attributes, and some items may be so strong that
	 * other stats are banned by default from generating. This is taken from the JSON,
	 * and passed through a system that creates a list of valid attributes. */
	/*-------------------------------------------------------------------------------*/

	EInv_ItemRarity ItemRarity = EInv_ItemRarity::Common;
	TArray<EInv_SecondaryAttributeRules> SecondaryAttributeRules;
};
/*-------------------------------------------------------------------------*/