#pragma once
#include "NativeGameplayTags.h"

namespace CyberscapeItems
{
	namespace Weapon
	{
		namespace Pistol
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Havoc)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Flare)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Totality)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Maverick)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Goliath)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Phantom)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comet)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(BigBang)
			
		}
		namespace MachineGun
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interfere)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Starfury)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dreadnaught)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Vector)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Atomizer)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(AutoRPEG)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Minigun)
		}
		namespace Shotgun
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SG234)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Chariot)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Oblivion)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Havoc)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Heartstopper)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Krakatoa)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shutdown)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stampede)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Brimstone)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hurricane)
		}
		namespace Rifle
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(MARS)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(PulseRifle)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Arkova)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sentinel)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Warhorse)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sublight)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Reaper)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(LtdSublight)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Frontier)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Annihilator)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(AntimatterRifle)
		}
		namespace Sniper
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Jupiter)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Icarus)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Saturn)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Eclipse)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ultramarine)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(DarkGalaxy)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Titan)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hornet)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sovereign)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Catastrophe)
		}
		namespace Exotic
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Houser)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Impact)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Kelvin)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(IonCannon)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sunbeam)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sulfurious)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Leviathan)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(ArcWeld)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Quasar)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Spartan)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pulsar)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pyrophor)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(FromTheAbyss)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(PortalGenerator)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Spritzal)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Trident)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Atomos)
		}
	}
	namespace Attachment
	{
		namespace Tracer
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Red)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Blue)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Green)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Subspectral)
		}
		namespace Dot
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Red)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Blue)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Green)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Subspectral)
		}
		namespace Laser
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Red)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Blue)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Green)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Subspectral)
		}
		namespace Scope
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Arc)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(OpticalZoom)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(DigitalHyperscan)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(LPVOSwitch)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(DarkHorizonTargetting)
		}
		namespace Modules
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(FusionCapacitor)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(HazChemBioreactor)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(GravitationalSuperradianceModule)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(PlasmaChargeConverter)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(ExplosiveShellPackage)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(HomingMissileBrain)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(PremiumTag)
			
		}
		namespace Launchers
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grenade)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Atomos)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(MegawattLaser)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(ChemSprayer)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(MiniFlamethrower)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(UnderbarrelRailgun)
		}
		namespace Bayonet
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sawsall)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Vibroblade)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(PlasmaTorch)
		}
	}
	namespace Material
	{
		namespace Part
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Nozzle)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cannister)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Thruster)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Controller)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Laser)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Lens)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(LogicBoard)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Receiver)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Electromagnet)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(EnergyProjector)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SmartSensor)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(RepairMatrix)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Alloy)          
		}
		namespace Metal
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Scrap)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Aluminum);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Copper);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gold);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Vanatium);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Voltanium);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rubidium);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tritanium);	
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Neutronium);
		}
		namespace Plastic
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Scrap);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Composite);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resin);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ceramopolymer);				
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Titanopolymer);
		}
		namespace Wire
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fiber);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Filament);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Multipurpose);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hypergravity);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(CryoStabilized);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Nanoweave);
		}
		namespace Coil
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Copper);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gold);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ion);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hyper);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Warp);
		}
		namespace Reactor
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Chemical);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fusion);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(GammaPulse);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(CompressedRedStar);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(CompressedBlueStar);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(QuantumGravity);
			
		}
		namespace Core
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Thermal);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Powerflux);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Megaflux);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gigaflux);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Singularity);
		}
		namespace Device
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Processor);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(IntellAI);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(QuantumComputer);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(MatrixCortex);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(CarbonMotherboard);
		}
		namespace Crystal
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Quartz);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Diamond);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(TransparentTungsten);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Galaxium);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dimensionite);
		}
		namespace Biological
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gloop);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ambergel);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Bactoviral);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Biorobotic);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Nanotechnetium);
		}
		namespace Catalyst
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Base);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Super);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Plasmatic);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ultra);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Nebulaic);	
		}
		namespace Plating
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Aluminum);     
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Copper);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rubidium);      
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tritanium);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Neutronium);   
		}
		namespace Special
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(LithiumDeuteride);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(ExoticIsotopes);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(WarpFabric);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(MetallicHydrazine);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(CovalentBond);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(LiquidPlutonium);
		}
	}
}